### ISSUE TITLE
gulp-sass version doesn't support OS X with latest node

### ISSUE THREAD

**Issue by robinleblon** [nystudio107/craft#1]
On OS X 10.12.6 with node v8.9.1 the following error shows up when trying to run `gulp build`.
Bumping gulp-sass to v3.1.0 solves the problem.

```
[21:04:17] 'scss' errored after 145 ms
[21:04:17] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/Users/robin/Sites/allesovermobiliteit/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/robin/Sites/allesovermobiliteit/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/robin/Sites/allesovermobiliteit/node_modules/gulp-sass/index.js:187:21)
```

**Comment by khalwat** [comment]
Fixed, thanks.

I didn't expect anyone to be using this quite yet (thus no release tags), it's still a work in progress... but keep any issues coming! :)
