### ISSUE TITLE
Craft Gulp Update

### ISSUE THREAD

**Issue by sahillangoo** [nystudio107/craft#42]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.
Please Update Glup Branch
its shows error every time I build

### Additional context
Add any other context or screenshots about the support request here.
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Development\frontend\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Development\repositories\frontend\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Development\repositories\frontend\gulpfile.js:55:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (C:\Development\repositories\frontend\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='

**Comment by khalwat** [comment]
It's unlikely I'm going to update this.
