### ISSUE TITLE
Webpack failing due to UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by johnnyhawley** [nystudio107/craft#46]
### Describe the bug
Webpack is exiting due to UnhandledPromiseRejectionWarning: TypeError: ManifestPlugin is not a constructor

```
UnhandledPromiseRejectionWarning: TypeError: ManifestPlugin is not a constructor
     at common (/var/www/project/buildchain/webpack-configs/manifest.config.js:12:13)
     at module.exports (/var/www/project/buildchain/webpack-configs/manifest.config.js:31:20)
     at getModernWebpackConfig (/var/www/project/buildchain/get-webpack-config.js:42:93)
     at names.forEach (/var/www/project/buildchain/get-webpack-config.js:52:52)
     at Array.forEach (<anonymous>)
     at webpackConfigs (/var/www/project/buildchain/get-webpack-config.js:52:11)
     at modernWebpackConfigs (/var/www/project/buildchain/get-webpack-config.js:76:44)
     at Object.<anonymous> (/var/www/project/buildchain/webpack.dev.js:11:18)
     at Module._compile (/var/www/project/buildchain/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
 (node:1553) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
 (node:1553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by cavellblood** [comment]
I happened to make this same fix before I noticed that you made this pull request. This fixed it for me too. Seems like it should have worked the original way but not sure why it didn't.

**Comment by khalwat** [comment]
This is really strange... they must have just recently changed this, it worked as-is before. Thx for the PR, will get it merged in!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft/releases/tag/2.4.9

**Comment by iuscare** [comment]
Really strange, when accepting the PR I get the same error @johnnyhawley and @cavellblood got without the PR. For me, it works without the PR. Which versions are you using?

```
webpack_1     | (node:47) UnhandledPromiseRejectionWarning: TypeError: WebpackManifestPlugin is not a constructor
webpack_1     |     at common (/var/www/project/buildchain/webpack-configs/manifest.config.js:12:7)
webpack_1     |     at module.exports (/var/www/project/buildchain/webpack-configs/manifest.config.js:31:12)
webpack_1     |     at getModernWebpackConfig (/var/www/project/buildchain/get-webpack-config.js:42:93)
webpack_1     |     at names.forEach (/var/www/project/buildchain/get-webpack-config.js:52:52)
webpack_1     |     at Array.forEach (<anonymous>)
webpack_1     |     at webpackConfigs (/var/www/project/buildchain/get-webpack-config.js:52:11)
webpack_1     |     at modernWebpackConfigs (/var/www/project/buildchain/get-webpack-config.js:76:44)
webpack_1     |     at Object.<anonymous> (/var/www/project/buildchain/webpack.dev.js:11:18)
webpack_1     |     at Module._compile (/var/www/project/buildchain/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
webpack_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
webpack_1     | (node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
webpack_1     | (node:47) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by khalwat** [comment]
@iuscare probably you have an older version of the WebpackManifestPlugin installed... delete your `package-lock.json` and do a `npm update`
