### ISSUE TITLE
Unable to use db with a "table prefix"

### ISSUE THREAD

**Issue by mortscode** [nystudio107/craft#53]
### Describe the bug
I was able to get the local dev up and running with the initial DB in place that comes with the repo.
I tried to put my DB in the `db-seed` folder and update the `.env` value for `DB_TABLE_PREFIX`, no luck.
I used Sequel Pro to dump the DB and import my DB, no luck.
My table prefix is `tmp_`, I've tried it with and without the underscore.

### To reproduce
Steps to reproduce the behaviour:
1. Pull down the environment
2. Put a gzipped DB in the `db-seed` folder
3. Update the `DB_TABLE_PREFIX` value to reflect the requirements for the new DB
4. Run `docker-compose up`

### Expected behaviour
Environment would fire up with the DB loaded into place and viewable in the CP

### Error
```
An Error occurred while handling another error:
craft\errors\SiteNotFoundException: No sites exist in /var/www/project/cms/vendor/craftcms/cms/src/web/Request.php:1462
Stack trace:
#0 /var/www/project/cms/vendor/craftcms/cms/src/web/Request.php(237): craft\web\Request->_requestedSite(NULL)
#1 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#5 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#6 /var/www/project/cms/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#7 [internal function]: {closure}()
#8 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(631): call_user_func_array(Object(Closure), Array)
#9 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#10 /var/www/project/cms/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#11 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(748): yii\di\ServiceLocator->get('request', true)
#12 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(324): yii\base\Module->get('request', true)
#13 /var/www/project/cms/vendor/yiisoft/yii2/web/Application.php(161): craft\web\Application->get('request')
#14 /var/www/project/cms/vendor/craftcms/cms/src/helpers/App.php(665): yii\web\Application->getRequest()
#15 /var/www/project/cms/vendor/craftcms/cms/src/config/app.php(246): craft\helpers\App::viewConfig()
#16 [internal function]: {closure}()
#17 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(631): call_user_func_array(Object(Closure), Array)
#18 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#19 /var/www/project/cms/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#20 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(748): yii\di\ServiceLocator->get('view', true)
#21 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(324): yii\base\Module->get('view', true)
#22 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(568): craft\web\Application->get('view')
#23 /var/www/project/cms/vendor/yiisoft/yii2/web/ErrorHandler.php(267): yii\base\Application->getView()
#24 /var/www/project/cms/vendor/yiisoft/yii2/web/ErrorHandler.php(127): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#25 /var/www/project/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(148): yii\web\ErrorHandler->renderException(Object(craft\errors\SiteNotFoundException))
#26 /var/www/project/cms/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(craft\errors\SiteNotFoundException))
#27 /var/www/project/cms/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException(Object(craft\errors\SiteNotFoundException))
#28 [internal function]: craft\web\ErrorHandler->handleException(Object(craft\errors\SiteNotFoundException))
#29 {main}
Previous exception:
craft\errors\SiteNotFoundException: No sites exist in /var/www/project/cms/vendor/craftcms/cms/src/web/Request.php:1462
Stack trace:
#0 /var/www/project/cms/vendor/craftcms/cms/src/web/Request.php(237): craft\web\Request->_requestedSite(NULL)
#1 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Request->init()
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#4 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Reque...', Array, Array)
#5 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Reque...', Array, Array)
#6 /var/www/project/cms/vendor/craftcms/cms/src/config/app.web.php(13): yii\BaseYii::createObject(Array)
#7 [internal function]: {closure}()
#8 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(631): call_user_func_array(Object(Closure), Array)
#9 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->invoke(Object(Closure), Array)
#10 /var/www/project/cms/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#11 /var/www/project/cms/vendor/yiisoft/yii2/base/Module.php(748): yii\di\ServiceLocator->get('request', true)
#12 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(324): yii\base\Module->get('request', true)
#13 /var/www/project/cms/vendor/yiisoft/yii2/web/Application.php(161): craft\web\Application->get('request')
#14 /var/www/project/cms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1415): yii\web\Application->getRequest()
#15 /var/www/project/cms/vendor/craftcms/cms/src/web/Application.php(90): craft\web\Application->_preInit()
#16 /var/www/project/cms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /var/www/project/cms/vendor/yiisoft/yii2/base/Application.php(212): yii\base\BaseObject->__construct(Array)
#18 [internal function]: yii\base\Application->__construct(Array)
#19 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#20 /var/www/project/cms/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /var/www/project/cms/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /var/www/project/cms/vendor/craftcms/cms/bootstrap/bootstrap.php(246): yii\BaseYii::createObject(Array)
#23 /var/www/project/cms/vendor/craftcms/cms/bootstrap/web.php(51): require('/var/www/projec...')
#24 /var/www/project/cms/web/index.php(20): require('/var/www/projec...')
#25 {main}
```

### Versions
- Plugin version:
- Craft version:

**Comment by khalwat** [comment]
so this isn't a bug... if I had to guess, perhaps you need to remove all of the Project Config stuff too, if you're going to be importing your own db. They work as a pair.

The starter db in the `db-seed` dir is only used the first time the project is started up, after that the database is already seeded, and it's never used again. If you want to remove the volumes that have that db, you can do:

```
docker-compose down -v
```

...and then the next time you bring up the project, the database volume won't exist, so it'll create it and use whatever is in the `db-seed` dir.
